const express=require('./like-express');
const app=express();
app.use((req,res,next)=>{
    console.log('请求开始：',req.method,req.url);
    next();
})
app.use((req,res,next)=>{
    req.cookies={
        userId:'abc123'
    }
    next();
})
app.use((req,res,next)=>{
    setTimeout(()=>{
        req.body={
            a:100,
            b:200
        }
        next();
    })  
})
app.use('/api',(req,res,next)=>{
    console.log('处理路由');
    next() 
})
app.get('/api',(req,res,next)=>{
    console.log('get路由');
    next() 
})
app.post('/api',(req,res,next)=>{
    console.log('post');
    next() 
})
app.get('/api/get-cookie',(req,res,next)=>{
    console.log('get-cookie');
    res.json(
        {
            errno:0,
            data:req.cookies   
        }
    )
})
app.post('/api/get-post-data',(req,res,next)=>{
    console.log('get-post-data');
    res.json(
        {
            errno:0,
            data:req.body   
        }
    )
})
app.use((req,res,next)=>{
    console.log('处理404路由');
    res.json({
        errno:1,
        msg:'404'
    })
})
app.listen(3003,()=>{
    console.log('running on 3003')
})